#!/bin/bash

# Run the command and capture its output
output=$(bootc upgrade --check)
message_file=/etc/motd.d/upgrade-message

# Check if the output starts with "No changes in" that means there are no updates available
if [[ $output == No\ changes\ in* ]]; then
  # empty motd file
  rm $message_file 2> /dev/null
elif [[ ! -f $message_file ]]; then

  bootc_image=$(bootc status --json | jq '.spec.image.image')
  versions=$(skopeo inspect --format json docker://"$bootc_image" | jq '.Labels | {rhel_ai_version: .["rhel.ai.version"], rhel_version: .["redhat.version-id"]}')
  rhel_ai_version=$(echo "$versions" | jq -r '.rhel_ai_version')
  rhel_version=$(echo "$versions" | jq -r '.rhel_version')

  # If upgrade available, write the output to the file
  echo "New Rhel AI version $rhel_ai_version build on $rhel_version rhel is available" > $message_file
  # shellcheck disable=SC2129
  echo "In order to upgrade to new version please run:" >> $message_file
  echo "bootc upgrade --apply" >> $message_file
  echo "Please note that the system will reboot after the upgrade" >> $message_file
fi
