#!/bin/bash

# Run the command and capture its output
output=$(bootc upgrade --check)
message_file=/etc/motd.d/upgrade-message

if [[ $output == Update\ available* ]] && [[ ! -f $message_file ]]; then

  if [[ ! -f $message_file ]]; then
    bootc_image=$(bootc status --json | jq '.spec.image.image' | tr -d '"')
    rhel_ai_version=$(skopeo inspect --format json "docker://$bootc_image" | jq '.Labels | .["rhel.ai.version"]')
    # If upgrade available, write the output to the file
    echo -e "\n\n   **   Attention!   ** \n** A new $rhel_ai_version version is available **\n\
** In order to apply it run: bootc upgrade --apply \n\
** Please note that the system will reboot after the upgrade ** \n\n"  > $message_file
  fi
else
  rm $message_file 2> /dev/null
fi
